import { Exercise } from '@/types';

/* Omit is a TypeScript utility type that takes an existing interface and produces a new type with one or more fields removed.
  So Omit<Exercise, "id"> means the shape of Exercise but without id field */
export const DEFAULT_EXERCISES: Omit<Exercise, 'id'>[] = [
  // -------- Chest --------
  { name: 'Flat Barbell Bench Press', muscleGroup: 'Chest', isDefault: true },
  { name: 'Incline Barbell Bench Press', muscleGroup: 'Chest', isDefault: true },
  { name: 'Flat Dumbbell Bench Press', muscleGroup: 'Chest', isDefault: true },
  { name: 'Incline Dumbbell Bench Press', muscleGroup: 'Chest', isDefault: true },
  { name: 'Flat Smith Bench Press', muscleGroup: 'Chest', isDefault: true },
  { name: 'Incline Smith Bench Press', muscleGroup: 'Chest', isDefault: true },
  { name: 'Dumbbell Fly', muscleGroup: 'Chest', isDefault: true },
  { name: 'Incline Dumbbell Fly', muscleGroup: 'Chest', isDefault: true },
  { name: 'Cable Fly', muscleGroup: 'Chest', isDefault: true },
  { name: 'Low Cable Fly', muscleGroup: 'Chest', isDefault: true },
  { name: 'High Cable Fly', muscleGroup: 'Chest', isDefault: true },
  { name: 'Push Up', muscleGroup: 'Chest', isDefault: true },
  { name: 'Incline Push Up', muscleGroup: 'Chest', isDefault: true },
  { name: 'Decline Push Up', muscleGroup: 'Chest', isDefault: true },
  { name: 'Chest Dip', muscleGroup: 'Chest', isDefault: true },
  { name: 'Pec Deck Fly', muscleGroup: 'Chest', isDefault: true },
  { name: 'Chest Press Machine', muscleGroup: 'Chest', isDefault: true },
  { name: 'Incline Chest Press Machine', muscleGroup: 'Chest', isDefault: true },

  // -------- Back --------
  { name: 'Barbell Deadlift', muscleGroup: 'Back', isDefault: true },
  { name: 'Trap Bar Deadlift', muscleGroup: 'Back', isDefault: true },
  { name: 'Rack Pull', muscleGroup: 'Back', isDefault: true },
  { name: 'Barbell Row', muscleGroup: 'Back', isDefault: true },
  { name: 'Reverse Grip Barbell Row', muscleGroup: 'Back', isDefault: true },
  { name: 'Pendlay Row', muscleGroup: 'Back', isDefault: true },
  { name: 'Chest Supported Dumbbell Row', muscleGroup: 'Back', isDefault: true },
  { name: 'Seated Cable Row', muscleGroup: 'Back', isDefault: true },
  { name: 'Wide Grip Seated Cable Row', muscleGroup: 'Back', isDefault: true },
  { name: 'Close Grip Seated Cable Row', muscleGroup: 'Back', isDefault: true },
  { name: 'Unilateral Seated Cable Row', muscleGroup: 'Back', isDefault: true },
  { name: 'Lat Pulldown', muscleGroup: 'Back', isDefault: true },
  { name: 'Wide Grip Lat Pulldown', muscleGroup: 'Back', isDefault: true },
  { name: 'Close Grip Lat Pulldown', muscleGroup: 'Back', isDefault: true },
  { name: 'Neutral Grip Lat Pulldown', muscleGroup: 'Back', isDefault: true },
  { name: 'Unilateral Lat Pulldown', muscleGroup: 'Back', isDefault: true },
  { name: 'Pull Up', muscleGroup: 'Back', isDefault: true },
  { name: 'Chin Up', muscleGroup: 'Back', isDefault: true },
  { name: 'Neutral Grip Pull Up', muscleGroup: 'Back', isDefault: true },
  { name: 'Wide Grip Pull Up', muscleGroup: 'Back', isDefault: true },
  { name: 'Assisted Pull Up', muscleGroup: 'Back', isDefault: true },
  { name: 'Lat Pullover Machine', muscleGroup: 'Back', isDefault: true },
  { name: 'Cable Pullover', muscleGroup: 'Back', isDefault: true },
  { name: 'T-Bar Row', muscleGroup: 'Back', isDefault: true },
  { name: 'Seated Row Machine', muscleGroup: 'Back', isDefault: true },
  { name: 'Low Row Machine', muscleGroup: 'Back', isDefault: true },
  { name: 'Back Extension', muscleGroup: 'Back', isDefault: true },
  { name: 'Barbell Shrug', muscleGroup: 'Back', isDefault: true },
  { name: 'Dumbbell Shrug', muscleGroup: 'Back', isDefault: true },
  { name: 'Smith Shrug', muscleGroup: 'Back', isDefault: true },

  // -------- Shoulders --------
  { name: 'Standing Barbell Overhead Press', muscleGroup: 'Shoulders', isDefault: true },
  { name: 'Seated Barbell Overhead Press', muscleGroup: 'Shoulders', isDefault: true },
  { name: 'Seated Smith Overhead Press', muscleGroup: 'Shoulders', isDefault: true },
  { name: 'Seated Dumbbell Overhead Press', muscleGroup: 'Shoulders', isDefault: true },
  { name: 'Standing Dumbbell Overhead Press', muscleGroup: 'Shoulders', isDefault: true },
  { name: 'Dumbbell Lateral Raise', muscleGroup: 'Shoulders', isDefault: true },
  { name: 'Cable Lateral Raise', muscleGroup: 'Shoulders', isDefault: true },
  { name: 'Lateral Raise Machine', muscleGroup: 'Shoulders', isDefault: true },
  { name: 'Dumbbell Front Raise', muscleGroup: 'Shoulders', isDefault: true },
  { name: 'Cable Front Raise', muscleGroup: 'Shoulders', isDefault: true },
  { name: 'EZ-Bar Upright Row', muscleGroup: 'Shoulders', isDefault: true },
  { name: 'Face Pull', muscleGroup: 'Shoulders', isDefault: true },
  { name: 'Rear Delt Cable Fly', muscleGroup: 'Shoulders', isDefault: true },
  { name: 'Unilateral Rear Delt Cable Fly', muscleGroup: 'Shoulders', isDefault: true },
  { name: 'Bent Over Dumbbell Reverse Fly', muscleGroup: 'Shoulders', isDefault: true },
  { name: 'Reverse Pec Deck Fly', muscleGroup: 'Shoulders', isDefault: true },
  { name: 'Shoulder Press Machine', muscleGroup: 'Shoulders', isDefault: true },

  // -------- Biceps --------
  { name: 'Barbell Curl', muscleGroup: 'Biceps', isDefault: true },
  { name: 'EZ-Bar Curl', muscleGroup: 'Biceps', isDefault: true },
  { name: 'Dumbbell Curl', muscleGroup: 'Biceps', isDefault: true },
  { name: 'Dumbbell Hammer Curl', muscleGroup: 'Biceps', isDefault: true },
  { name: 'Dumbbell Cross Body Hammer Curl', muscleGroup: 'Biceps', isDefault: true },
  { name: 'Incline Dumbbell Curl', muscleGroup: 'Biceps', isDefault: true },
  { name: 'EZ-Bar Preacher Curl', muscleGroup: 'Biceps', isDefault: true },
  { name: 'Dumbbell Preacher Curl', muscleGroup: 'Biceps', isDefault: true },
  { name: 'Preacher Curl Machine', muscleGroup: 'Biceps', isDefault: true },
  { name: 'Cable Curl', muscleGroup: 'Biceps', isDefault: true },
  { name: 'Unilateral Cable Curl', muscleGroup: 'Biceps', isDefault: true },
  { name: 'Cable Hammer Curl', muscleGroup: 'Biceps', isDefault: true },
  { name: 'Unilateral Cable Hammer Curl', muscleGroup: 'Biceps', isDefault: true },
  { name: 'Dumbbell Concentration Curl', muscleGroup: 'Biceps', isDefault: true },
  { name: 'Dumbbell Spider Curl', muscleGroup: 'Biceps', isDefault: true },
  { name: 'EZ-Bar Spider Curl', muscleGroup: 'Biceps', isDefault: true },
  { name: 'Recline Dumbbell Curl', muscleGroup: 'Biceps', isDefault: true },
  { name: 'Cable Bayesian Curl', muscleGroup: 'Biceps', isDefault: true },

  // -------- Triceps --------
  { name: 'Close Grip Barbell Bench Press', muscleGroup: 'Triceps', isDefault: true },
  { name: 'Close Grip Smith Bench Press', muscleGroup: 'Triceps', isDefault: true },
  { name: 'Barbell JM Press', muscleGroup: 'Triceps', isDefault: true },
  { name: 'Smith JM Press', muscleGroup: 'Triceps', isDefault: true },
  { name: 'Tricep Straight Bar Pushdown', muscleGroup: 'Triceps', isDefault: true },
  { name: 'Tricep Rope Pushdown', muscleGroup: 'Triceps', isDefault: true },
  { name: 'Dumbbell Overhead Tricep Extension', muscleGroup: 'Triceps', isDefault: true },
  { name: 'Cable Overhead Tricep Extension', muscleGroup: 'Triceps', isDefault: true },
  { name: 'Unilateral Cable Overhead Tricep Extension', muscleGroup: 'Triceps', isDefault: true },
  { name: 'EZ-Bar Overhead Tricep Extension', muscleGroup: 'Triceps', isDefault: true },
  { name: 'EZ-Bar Skull Crusher', muscleGroup: 'Triceps', isDefault: true },
  { name: 'Dumbbell Skull Crusher', muscleGroup: 'Triceps', isDefault: true },
  { name: 'Tricep Dip', muscleGroup: 'Triceps', isDefault: true },
  { name: 'Diamond Push Up', muscleGroup: 'Triceps', isDefault: true },

  // -------- Forearms --------
  { name: 'Dumbbell Wrist Curl', muscleGroup: 'Forearms', isDefault: true },
  { name: 'Dumbbell Wrist Extension', muscleGroup: 'Forearms', isDefault: true },
  { name: 'Reverse Dumbbell Curl', muscleGroup: 'Forearms', isDefault: true },
  { name: 'Reverse Barbell Curl', muscleGroup: 'Forearms', isDefault: true },
  { name: 'Reverse EZ-Bar Curl', muscleGroup: 'Forearms', isDefault: true },
  { name: 'Cable Wrist Curl', muscleGroup: 'Forearms', isDefault: true },
  { name: 'Cable Wrist Extension', muscleGroup: 'Forearms', isDefault: true },

  // -------- Quads --------
  { name: 'Barbell Squat', muscleGroup: 'Quads', isDefault: true },
  { name: 'Smith Squat', muscleGroup: 'Quads', isDefault: true },
  { name: 'Goblet Squat', muscleGroup: 'Quads', isDefault: true },
  { name: 'Barbell Front Squat', muscleGroup: 'Quads', isDefault: true },
  { name: 'Smith Front Squat', muscleGroup: 'Quads', isDefault: true },
  { name: 'Hack Squat', muscleGroup: 'Quads', isDefault: true },
  { name: 'Pendulum Squat', muscleGroup: 'Quads', isDefault: true },
  { name: 'Belt Squat', muscleGroup: 'Quads', isDefault: true },
  { name: 'Leg Press', muscleGroup: 'Quads', isDefault: true },
  { name: 'Unilateral Leg Press', muscleGroup: 'Quads', isDefault: true },
  { name: 'Leg Extension', muscleGroup: 'Quads', isDefault: true },
  { name: 'Unilateral Leg Extension', muscleGroup: 'Quads', isDefault: true },
  { name: 'Smith Bulgarian Split Squat', muscleGroup: 'Quads', isDefault: true },
  { name: 'Dumbbell Bulgarian Split Squat', muscleGroup: 'Quads', isDefault: true },
  { name: 'Smith Split Squat', muscleGroup: 'Quads', isDefault: true },
  { name: 'Dumbbell Split Squat', muscleGroup: 'Quads', isDefault: true },
  { name: 'Dumbbell Lunge', muscleGroup: 'Quads', isDefault: true },
  { name: 'Walking Dumbbell Lunge', muscleGroup: 'Quads', isDefault: true },
  { name: 'Reverse Dumbbell Lunge', muscleGroup: 'Quads', isDefault: true },

  // -------- Hamstrings --------
  { name: 'Barbell Romanian Deadlift', muscleGroup: 'Hamstrings', isDefault: true },
  { name: 'Smith Romanian Deadlift', muscleGroup: 'Hamstrings', isDefault: true },
  { name: 'Dumbbell Romanian Deadlift', muscleGroup: 'Hamstrings', isDefault: true },
  { name: 'Barbell Stiff Leg Deadlift', muscleGroup: 'Hamstrings', isDefault: true },
  { name: 'Smith Stiff Leg Deadlift', muscleGroup: 'Hamstrings', isDefault: true },
  { name: 'Dumbbell Stiff Leg Deadlift', muscleGroup: 'Hamstrings', isDefault: true },
  { name: 'Seated Leg Curl', muscleGroup: 'Hamstrings', isDefault: true },
  { name: 'Lying Leg Curl', muscleGroup: 'Hamstrings', isDefault: true },
  { name: 'Standing Leg Curl', muscleGroup: 'Hamstrings', isDefault: true },
  { name: 'Nordic Curl', muscleGroup: 'Hamstrings', isDefault: true },
  { name: 'Barbell Good Morning', muscleGroup: 'Hamstrings', isDefault: true },
  { name: 'Smith Good Morning', muscleGroup: 'Hamstrings', isDefault: true },

  // -------- Glutes --------
  { name: 'Hip Thrust Machine', muscleGroup: 'Glutes', isDefault: true },
  { name: 'Unilateral Hip Thrust Machine', muscleGroup: 'Glutes', isDefault: true },
  { name: 'Barbell Hip Thrust', muscleGroup: 'Glutes', isDefault: true },
  { name: 'Unilateral Barbell Hip Thrust', muscleGroup: 'Glutes', isDefault: true },
  { name: 'Smith Hip Thrust', muscleGroup: 'Glutes', isDefault: true },
  { name: 'Unilateral Smith Hip Thrust', muscleGroup: 'Glutes', isDefault: true },
  { name: 'Glute Bridge', muscleGroup: 'Glutes', isDefault: true },
  { name: 'Cable Pull Through', muscleGroup: 'Glutes', isDefault: true },
  { name: 'Cable Glute Kickback', muscleGroup: 'Glutes', isDefault: true },
  { name: 'Cable Hip Abduction', muscleGroup: 'Glutes', isDefault: true },
  { name: 'Hip Abductor Machine', muscleGroup: 'Glutes', isDefault: true },
  { name: 'Box Stepup', muscleGroup: 'Glutes', isDefault: true },

  // -------- Adductors --------
  { name: 'Hip Adductor Machine', muscleGroup: 'Adductors', isDefault: true },
  { name: 'Cable Hip Adduction', muscleGroup: 'Adductors', isDefault: true },

  // -------- Calves --------
  { name: 'Standing Calf Raise', muscleGroup: 'Calves', isDefault: true },
  { name: 'Seated Calf Raise', muscleGroup: 'Calves', isDefault: true },
  { name: 'Leg Press Calf Raise', muscleGroup: 'Calves', isDefault: true },
  { name: 'Unilateral Standing Calf Raise', muscleGroup: 'Calves', isDefault: true },
  { name: 'Tibialis Raise', muscleGroup: 'Calves', isDefault: true },

  // -------- Core --------
  { name: 'Cable Crunch', muscleGroup: 'Core', isDefault: true },
  { name: 'Hanging Leg Raise', muscleGroup: 'Core', isDefault: true },
  { name: 'Hanging Knee Raise', muscleGroup: 'Core', isDefault: true },
  { name: 'Lying Leg Raise', muscleGroup: 'Core', isDefault: true },
  { name: 'Crunch', muscleGroup: 'Core', isDefault: true },
  { name: 'Decline Crunch', muscleGroup: 'Core', isDefault: true },
  { name: 'Sit Up', muscleGroup: 'Core', isDefault: true },
  { name: 'Ab Crunch Machine', muscleGroup: 'Core', isDefault: true },
  { name: 'Russian Twist', muscleGroup: 'Core', isDefault: true },
  { name: 'Pallof Press', muscleGroup: 'Core', isDefault: true },
];
